### ISSUE TITLE
ModuleNotFoundError: No module named 'pyannote.audio.pipelines'

### ISSUE THREAD

**Issue by zoughi** [pyannote/pyannote-audio-demo#5]
hi
when I want to run the following demo:
"https://github.com/pyannote/pyannote-audio-demo" 
I get the following error: 
"ModuleNotFoundError: No module named 'pyannote.audio.pipelines'"

where should I download "pipelines" module?

best regards

**Comment by hbredin** [comment]
This demo relies in (still in development) pyannote.audio 2.0.
Check this installation instructions in [develop branch](https://github.com/pyannote/pyannote-audio/tree/develop)

**Comment by zoughi** [comment]
It worked fine!
thank you very much for your good documentation.
